-- H2 In-Memory Schema for perf-demo

CREATE TABLE IF NOT EXISTS PERF_PRODUCT (
    PRODUCT_ID    VARCHAR(20)    NOT NULL,
    PRODUCT_NAME  VARCHAR(200)   NOT NULL,
    CATEGORY      VARCHAR(50)    NOT NULL,
    PRICE         BIGINT         DEFAULT 0 NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PERF_ORDER (
    ORDER_ID       VARCHAR(20)    NOT NULL,
    CUSTOMER_ID    VARCHAR(20)    NOT NULL,
    CUSTOMER_NAME  VARCHAR(100)   NOT NULL,
    ORDER_STATUS   VARCHAR(20)    DEFAULT 'PENDING' NOT NULL,
    TOTAL_AMOUNT   BIGINT         DEFAULT 0 NOT NULL,
    ORDER_DATE     VARCHAR(10)    NOT NULL,
    CREATED_AT     VARCHAR(20)    NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE IF NOT EXISTS PERF_ORDER_DETAIL (
    DETAIL_ID     VARCHAR(20)    NOT NULL,
    ORDER_ID      VARCHAR(20)    NOT NULL,
    PRODUCT_ID    VARCHAR(20)    NOT NULL,
    PRODUCT_NAME  VARCHAR(200)   NOT NULL,
    QUANTITY      INT            DEFAULT 1 NOT NULL,
    UNIT_PRICE    BIGINT         DEFAULT 0 NOT NULL,
    LINE_AMOUNT   BIGINT         DEFAULT 0 NOT NULL,
    PRIMARY KEY (DETAIL_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES PERF_ORDER(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PERF_PRODUCT(PRODUCT_ID)
);
