-- ============================================================
-- perf-demo: 테이블 생성 스크립트
-- 실행 순서: 01-create-tables.sql → 02-insert-test-data.sql
-- ============================================================

-- 기존 테이블 삭제 (역순)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERF_ORDER_DETAIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERF_ORDER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERF_PRODUCT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 시퀀스 삭제
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PERF_ORDER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PERF_ORDER_DETAIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PERF_PRODUCT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- 1. PERF_PRODUCT (상품 마스터 - 1천건)
-- ============================================================
CREATE TABLE PERF_PRODUCT (
    PRODUCT_ID    VARCHAR2(20)   NOT NULL,
    PRODUCT_NAME  VARCHAR2(200)  NOT NULL,
    CATEGORY      VARCHAR2(50)   NOT NULL,
    PRICE         NUMBER(12)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PERF_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

COMMENT ON TABLE  PERF_PRODUCT              IS '성능테스트 상품 마스터';
COMMENT ON COLUMN PERF_PRODUCT.PRODUCT_ID   IS '상품ID';
COMMENT ON COLUMN PERF_PRODUCT.PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN PERF_PRODUCT.CATEGORY     IS '카테고리';
COMMENT ON COLUMN PERF_PRODUCT.PRICE        IS '단가';

-- ============================================================
-- 2. PERF_ORDER (주문 마스터 - 10만건)
-- ============================================================
CREATE TABLE PERF_ORDER (
    ORDER_ID       VARCHAR2(20)   NOT NULL,
    CUSTOMER_ID    VARCHAR2(20)   NOT NULL,
    CUSTOMER_NAME  VARCHAR2(100)  NOT NULL,
    ORDER_STATUS   VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    TOTAL_AMOUNT   NUMBER(15)     DEFAULT 0 NOT NULL,
    ORDER_DATE     VARCHAR2(10)   NOT NULL,
    CREATED_AT     VARCHAR2(20)   NOT NULL,
    CONSTRAINT PK_PERF_ORDER PRIMARY KEY (ORDER_ID)
);

COMMENT ON TABLE  PERF_ORDER               IS '성능테스트 주문 마스터';
COMMENT ON COLUMN PERF_ORDER.ORDER_ID      IS '주문ID';
COMMENT ON COLUMN PERF_ORDER.CUSTOMER_ID   IS '고객ID';
COMMENT ON COLUMN PERF_ORDER.CUSTOMER_NAME IS '고객명';
COMMENT ON COLUMN PERF_ORDER.ORDER_STATUS  IS '주문상태 (PENDING/CONFIRMED/SHIPPED/DELIVERED/CANCELLED)';
COMMENT ON COLUMN PERF_ORDER.TOTAL_AMOUNT  IS '총 금액';
COMMENT ON COLUMN PERF_ORDER.ORDER_DATE    IS '주문일 (YYYY-MM-DD)';
COMMENT ON COLUMN PERF_ORDER.CREATED_AT    IS '생성일시 (YYYY-MM-DD HH24:MI:SS)';

-- ============================================================
-- 3. PERF_ORDER_DETAIL (주문 상세 - 50만건)
-- ============================================================
CREATE TABLE PERF_ORDER_DETAIL (
    DETAIL_ID     VARCHAR2(20)   NOT NULL,
    ORDER_ID      VARCHAR2(20)   NOT NULL,
    PRODUCT_ID    VARCHAR2(20)   NOT NULL,
    PRODUCT_NAME  VARCHAR2(200)  NOT NULL,
    QUANTITY      NUMBER(5)      DEFAULT 1 NOT NULL,
    UNIT_PRICE    NUMBER(12)     DEFAULT 0 NOT NULL,
    LINE_AMOUNT   NUMBER(15)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PERF_ORDER_DETAIL PRIMARY KEY (DETAIL_ID),
    CONSTRAINT FK_PERF_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PERF_ORDER(ORDER_ID),
    CONSTRAINT FK_PERF_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PERF_PRODUCT(PRODUCT_ID)
);

COMMENT ON TABLE  PERF_ORDER_DETAIL               IS '성능테스트 주문 상세';
COMMENT ON COLUMN PERF_ORDER_DETAIL.DETAIL_ID     IS '상세ID';
COMMENT ON COLUMN PERF_ORDER_DETAIL.ORDER_ID      IS '주문ID (FK)';
COMMENT ON COLUMN PERF_ORDER_DETAIL.PRODUCT_ID    IS '상품ID (FK)';
COMMENT ON COLUMN PERF_ORDER_DETAIL.PRODUCT_NAME  IS '상품명 (비정규화)';
COMMENT ON COLUMN PERF_ORDER_DETAIL.QUANTITY       IS '수량';
COMMENT ON COLUMN PERF_ORDER_DETAIL.UNIT_PRICE    IS '단가';
COMMENT ON COLUMN PERF_ORDER_DETAIL.LINE_AMOUNT   IS '항목 금액 (수량 * 단가)';

-- 주의: 인덱스는 의도적으로 생성하지 않음 (Scenario 2 병목 시연용)
-- 최적화 시 03-create-indexes.sql 실행
